FROM node:18-alpine
WORKDIR /app

COPY package*.json ./
RUN rm -rf node_modules package-lock.json && \
    npm install --no-optional && \
    npm cache clean --force

COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev"]